site_name: Gobblin Documentation
site_description: Documentation for Gobblin, a universal data ingestion framework for Hadoop
site_author: Abhishek Tiwari, Chavdar Botev, Issac Buenrostro, Min Tu, Narasimha Veeramreedy, Pradhan Cadabam, Sahil Takiar, Shirshanka Das, Yinan Li, Ying Dai, Ziyang Liu

repo_url: https://github.com/linkedin/gobblin
repo_name: Gobblin

docs_dir: gobblin-docs

pages:
    - Home: index.md
    - Getting Started: Getting-Started.md
    - Architecture: Gobblin-Architecture.md
    - User Guide:
        - Job Configuration Files: user-guide/Working-with-Job-Configuration-Files.md
        - Deployment: user-guide/Gobblin-Deployment.md
        - Gobblin on Yarn: user-guide/Gobblin-on-Yarn.md
        - Compaction: user-guide/Compaction.md
        - State Management and Watermarks: user-guide/State-Management-and-Watermarks.md
        - Fork Operator: user-guide/Working-with-the-ForkOperator.md
        - Configuration Glossary: user-guide/Configuration-Properties-Glossary.md
        - Partitioned Writers: user-guide/Partitioned-Writers.md
        - Monitoring: user-guide/Monitoring.md
        - Schedulers: user-guide/Gobblin-Schedulers.md
        - Job Execution History Store: user-guide/Job-Execution-History-Store.md
        - Gobblin Build Options: user-guide/Gobblin-Build-Options.md
        - Troubleshooting: user-guide/Troubleshooting.md
        - FAQs: user-guide/FAQs.md
    - Case Studies:
        - Kafka-HDFS Ingestion: case-studies/Kafka-HDFS-Ingestion.md
        - Publishing Data to S3: case-studies/Publishing-Data-to-S3.md
